import React from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Bell, ChevronRight, Coins, Disc3, Home, Settings, Trophy, Users, Zap, ShoppingBag, Target, LockKeyhole, Play, Radio } from 'lucide-react'
import { useGameStore } from './store'

const nav = [
  { name: 'Home', icon: Home }, { name: 'Spin', icon: Disc3, badge: '3' }, { name: 'Skuad', icon: Users },
  { name: 'Transfer', icon: ShoppingBag }, { name: 'Kompetisi', icon: Trophy }, { name: 'Klub', icon: Radio }, { name: 'Misi', icon: Target }
]
const tiles = [
  { title:'SPIN PEMAIN', sub:'Temukan bintang berikutnya', tab:'Spin', icon:Disc3, color:'#4ee8ff', gradient:'from-cyan-950 to-blue-900' },
  { title:'SKUAD UTAMA', sub:'Bangun Dream XI kamu', tab:'Skuad', icon:Users, color:'#9e7bff', gradient:'from-violet-950 to-indigo-900' },
  { title:'KOMPETISI', sub:'Musim baru menanti', tab:'Kompetisi', icon:Trophy, color:'#ffbb55', gradient:'from-amber-950 to-orange-900' },
  { title:'TRANSFER HUB', sub:'Pasar pemain harian', tab:'Transfer', icon:ShoppingBag, color:'#57e39b', gradient:'from-emerald-950 to-teal-900' },
]

function App() {
  const { activeTab, setTab, manager, wallet } = useGameStore()
  return <div className="min-h-screen grid-bg relative overflow-hidden">
    <div className="portrait-lock"><div><div className="text-5xl mb-5">↻</div><h2 className="condensed text-3xl font-bold italic">PUTAR LAYAR</h2><p className="text-slate-400 mt-2">Sanzz Football dirancang untuk landscape.</p></div></div>
    <div className="absolute -top-48 -right-40 w-[700px] h-[700px] rounded-full bg-cyan-500/10 blur-[130px] pointer-events-none" />
    <div className="absolute bottom-[-280px] left-[-100px] w-[650px] h-[650px] rounded-full bg-violet-600/10 blur-[130px] pointer-events-none" />
    <header className="h-[84px] px-8 flex items-center justify-between border-b border-white/10 bg-[#07111f]/80 backdrop-blur-xl relative z-10">
      <div className="flex items-center gap-7"><div className="flex items-center gap-3"><div className="w-11 h-11 angled bg-cyan-400 text-[#07111f] flex items-center justify-center font-black italic text-xl">SF</div><div><div className="condensed italic font-bold text-2xl tracking-wide">SANZZ <span className="text-cyan-300">FOOTBALL</span></div><div className="text-[9px] text-slate-500 tracking-[.35em]">MANAGER MODE</div></div></div>
      <nav className="hidden xl:flex gap-1">{nav.map(({name,icon:Icon,badge})=><button key={name} onClick={()=>setTab(name)} className={`relative flex items-center gap-2 px-3 py-3 text-xs font-bold transition ${activeTab===name?'text-cyan-300':'text-slate-400 hover:text-white'}`}><Icon size={16}/>{name}{badge&&<span className="absolute right-1 top-1 rounded-full bg-rose-500 text-[9px] px-1.5 text-white">{badge}</span>}{activeTab===name&&<motion.div layoutId="nav" className="absolute bottom-0 left-2 right-2 h-0.5 bg-cyan-300"/>}</button>)}</nav></div>
      <div className="flex items-center gap-4"><div className="hidden md:flex items-center gap-5 text-xs"><span className="flex items-center gap-1.5 text-amber-300"><Coins size={15}/>{wallet.coins.toLocaleString()}</span><span className="text-emerald-300">$ {(wallet.cash/1000000).toFixed(2)}M</span><span className="flex items-center gap-1 text-cyan-300"><Disc3 size={15}/>{wallet.tickets}</span></div><div className="h-8 w-px bg-white/10"/><button className="relative text-slate-400 hover:text-white"><Bell size={19}/><i className="absolute -right-1 -top-1 w-2 h-2 bg-rose-400 rounded-full"/></button><button className="text-slate-400 hover:text-white"><Settings size={19}/></button><div className="w-10 h-10 rounded-full border-2 border-cyan-400/50 bg-gradient-to-br from-slate-600 to-slate-900 flex items-center justify-center font-bold">S</div></div>
    </header>
    <main className="relative z-0 max-w-[1800px] mx-auto px-8 py-8 h-[calc(100vh-132px)] overflow-auto"><AnimatePresence mode="wait"><motion.div key={activeTab} initial={{opacity:0,x:18}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-18}} transition={{duration:.2}}>{activeTab==='Home'?<Home setTab={setTab} manager={manager}/>:<Placeholder tab={activeTab} setTab={setTab}/>}</motion.div></AnimatePresence></main>
    <footer className="fixed bottom-0 left-0 right-0 h-12 px-8 flex items-center justify-between bg-[#050b14]/90 border-t border-white/10 text-[10px] tracking-wider text-slate-500 z-20"><span><kbd>ESC</kbd> KEMBALI</span><span className="text-slate-600">SANZZ FOOTBALL  •  SEASON 01</span><span><kbd>ENTER</kbd> PILIH <span className="ml-5"><kbd>Q</kbd> DETAIL</span></span></footer>
  </div>
}
function Home({setTab,manager}) { return <div className="space-y-7"><section className="grid grid-cols-[1fr_350px] gap-6"><div className="glass rounded-xl p-9 min-h-[255px] relative overflow-hidden shine"><div className="absolute right-0 top-0 w-1/2 h-full opacity-40 bg-[radial-gradient(ellipse_at_center,#1e8ca9,transparent_65%)]"/><div className="relative"><div className="flex items-center gap-2 text-cyan-300 text-xs font-bold tracking-[.25em]"><Zap size={14}/> LIVE EVENT  •  SEASON 01</div><h1 className="condensed italic font-bold text-6xl mt-4 leading-none">THE ROAD TO<br/><span className="text-cyan-300">GLORY</span></h1><p className="text-slate-400 text-sm mt-4">Mulai dari nol. Bangun legenda sepak bolamu.</p><button onClick={()=>setTab('Kompetisi')} className="angled mt-6 px-7 py-3 bg-cyan-300 text-[#06101d] text-xs font-black hover:bg-white transition flex items-center gap-2">MULAI MUSIM <ChevronRight size={16}/></button></div><div className="absolute right-12 bottom-5 text-[130px] opacity-10">⚽</div></div><div className="glass rounded-xl p-6"><div className="text-xs text-slate-400 uppercase tracking-widest">Manager profile</div><div className="flex items-center gap-4 mt-5"><div className="w-20 h-20 rounded-full bg-gradient-to-br from-cyan-400 to-violet-700 flex items-center justify-center text-3xl font-black italic">S</div><div><h3 className="condensed text-3xl italic font-bold">{manager.name}</h3><p className="text-cyan-300 text-xs">LEVEL {manager.level} <span className="text-slate-500">• ROOKIE</span></p></div></div><div className="mt-6"><div className="flex justify-between text-[10px] text-slate-500 mb-2"><span>XP PROGRESS</span><span>0 / 1,000</span></div><div className="h-1.5 bg-slate-800 rounded-full"><div className="h-full w-[18%] bg-cyan-300 rounded-full"/></div></div></div></section><section><div className="flex items-end justify-between mb-4"><div><p className="text-cyan-300 text-xs font-bold tracking-[.25em]">YOUR JOURNEY</p><h2 className="condensed text-4xl font-bold italic">MANAGER HUB</h2></div><button className="text-xs text-slate-400 hover:text-white flex items-center gap-1">LIHAT SEMUA <ChevronRight size={14}/></button></div><div className="grid grid-cols-4 gap-4">{tiles.map(({title,sub,tab,icon:Icon,color,gradient},i)=><motion.button whileHover={{y:-5}} key={title} onClick={()=>setTab(tab)} className={`glass rounded-xl p-5 text-left min-h-[155px] relative overflow-hidden bg-gradient-to-br ${gradient}`}><Icon size={27} color={color}/><h3 className="condensed italic text-2xl font-bold mt-5">{title}</h3><p className="text-xs text-slate-400 mt-1">{sub}</p>{i===0&&<span className="absolute top-4 right-4 text-[9px] bg-rose-500 px-2 py-1 font-bold angled">BARU</span>}<span className="absolute -right-3 -bottom-8 text-8xl opacity-5">{i===0?'◉':i===1?'✦':i===2?'♜':'◆'}</span></motion.button>)}</div></section></div> }
function Placeholder({tab,setTab}) { return <div className="min-h-[70vh] flex items-center justify-center"><div className="glass rounded-2xl p-12 text-center max-w-lg"><LockKeyhole className="mx-auto text-cyan-300" size={42}/><h1 className="condensed italic text-5xl font-bold mt-5">{tab.toUpperCase()}</h1><p className="text-slate-400 mt-3">Modul {tab} sedang disiapkan untuk fase berikutnya. Fondasi manager kamu sudah tersimpan.</p><button onClick={()=>setTab('Home')} className="angled mt-7 px-7 py-3 bg-white/10 hover:bg-cyan-300 hover:text-[#07111f] text-xs font-bold transition">KEMBALI KE HOME</button></div></div> }
export default App
